FROM tensorflow/tensorflow:2.5.0-gpu

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/ultralytics/yolov5.git /yolov5
WORKDIR /yolov5

RUN pip install -r requirements.txt

COPY train.py /yolov5/train.py
COPY predict.py /yolov5/predict.py

ENTRYPOINT ["python", "/yolov5/predict.py"]
